forwards:
- source: -1001569318987
  dest:
  - -1001289298028
  offset: 288
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
admins: []
plugins:
  filter:
    text:
      blacklist:
      - badword
    files:
      whitelist:
      - document
      - video
