admins: []
forwards:
- source: -1001462261759
  dest:
  - -1001325755519
  offset: 0
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
