admins: []
forwards:
- source: -1001538472738
  dest:
  - -1001591273518
  offset: 2817
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
