admins: []
forwards:
- source: -1001774883876
  dest:
  - -1001543396091
  offset: 5701
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
