forwards:
- source: -1001591273518
  dest:
  - -1001681867526
  offset: 6484
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
admins: []
